### ISSUE TITLE
Floating arandr sometimes needs click sometimes not

### ISSUE THREAD

**Issue by developer1105** [baskerville/bspwm#1374]
When running arandr in floating mode (it is configured to open as floating) sometimes it shows on screen immediately, and other times, I need to click anywhere on the screen so that it appears. Why does this happen?

This is the line related to arandr in bspwmrc file:
bspc rule -a Arandr state=floating focus=on follow=on

**Comment by emanuele6** [comment]
probably the same bug as #935; it has been fixed in the most recent commit: 1560df35be303807052c235634eb8d59415c37ff

**Comment by developer1105** [comment]
I'm using "bspwm-git 0.9.10.r33.ge22d0fa-1" from aur repositories.
The latest update was on 2022-04-11. The issue still remains.
I don't know if arandr being a python script has someting to do with it, but anyways...

**Comment by Azorlogh** [comment]
I can confirm the same issue here, happening with a bunch of other floating windows. Most annoyingly, it happens with file dialogs too
On version: `0.9.10-33-ge22d0fa`

**Comment by ortango** [comment]
>On version: 0.9.10-33-ge22d0fa

according to that version string you are using a build older then the fix... https://github.com/baskerville/bspwm/compare/e22d0fad23e0e85b401be69f2360a1c3a0767921...1560df35be303807052c235634eb8d59415c37ff

**Comment by Azorlogh** [comment]
Ah my bad sorry :facepalm: I will upgrade and report back
I don't quite understand how that versioning is derived, I thought it was a commit hash originally but it doesn't seem to be
