### ISSUE TITLE
_NET_DESKTOP_NAMES not consistent with config

### ISSUE THREAD

**Issue by sometimesnaive** [baskerville/bspwm#297]
Hi, 

When I tried to use tint2 as the panel for bspwm, I discovered that desktop name was incorrectly displayed on tint2. Since tint2 reads from _NET_DESKTOP_NAMES, this is the result I get for
```
xprop -root _NET_DESKTOP_NAMES
```
is
```
_NET_DESKTOP_NAMES(UTF8_STRING) = "dustbin", "2", "3", ""
```

but in my config I set desktop names with
```
bspc monitor -d main light dustbin
```

What's the problem?

**Comment by baskerville** [comment]
It should be fixed by fc34011.

**Comment by sometimesnaive** [comment]
Reopening because it's not completely resolved. 

When user dynamically adds desktop by using ``` bspc -a ``` outside initial config, then quit by ```bspc quit``` and log back in,  _NET_DESKTOP_NAMES in this case will not be the initial config file value.

**Comment by baskerville** [comment]
Can you provide instructions on how to reproduce?

**Comment by sometimesnaive** [comment]
Never mind sorry. I have done a bit debugging and it turns out that in my environment the xfce4-settingsd  seems to be applying desktop names value stored before, thus overwriting the effects of ``` bspc monitor```. Getting rid of the config daemon seems to fix this.
