### ISSUE TITLE
node id being trimmed in subscribe calls

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#361]
Okay, this is a bit of a weird one -- a node/window with id `0x0800003` gets the first 0 after the x cut, resulting in `0x800003` in a `bspc subscribe node_*` call. I can `bspc query` the desktop and see the right id printed, but the wrong one shows in the subscribe call. This is reproducible here after with only that id, which re-occurs between different bspwm sessions for me. 

unsure if it's relevant, existing monitors/desktops are in this naming scheme:
```
$ bspc query -D
1/00
1/01
1/10
1/11
2/00
2/01
2/10
2/11
3/00
3/01
3/10
3/11
```

the specific command I'm using is: `bspc subscribe node_focus node_unmanage`

edit: happened with a similarly named id as well, heres a webm: https://u.teknik.io/M2d5Qg.webm

**Comment by baskerville** [comment]
Well I could use `0x%07x` as *printf* format instead of `0x%x`. That might be a cosmetic improvement.

Where did you get the zero-padded version from?

**Comment by neeasade** [comment]
from the query for the current window id with bspc -- the webm above shows.

**Comment by neeasade** [comment]
:+1:

**Comment by baskerville** [comment]
*i3-wm* uses `0x%08x` and [lsw](http://tools.suckless.org/lsw) uses `0x%07lx`.

Not sure what the proper format is.

**Comment by neeasade** [comment]
xprop appears to use `0x%lx`. unsure as well.

**Comment by neeasade** [comment]
hm, seeing the same issue, and it's affecting bspc commands -- eg if I `bspc query -N -n .leaf` and get some node ID's that are trimmed, I can't `bspc config -n $nodeId border_width $some_width` after -- the command will fail on windows whose ID was queried and returned the 'trimmed' version.

**Comment by neeasade** [comment]
also maybe of note, I have 3 monitors, and only 3 window node ID's are trimmed - outputs:

[bspc wm -d | jshon](http://sprunge.us/OeXg)
[bspc query -N](http://sprunge.us/OeXg)

**Comment by baskerville** [comment]
I'm unable to reproduce: setting the border width of a leaf always works for me.

The IDs are parsed via `strtol`, so anything goes.

**Comment by neeasade** [comment]
alright -- just to show, here's a [webm](https://u.teknik.io/6F0PD.webm). will re-check update status for sanity later.

**Comment by baskerville** [comment]
Should be fixed as of 1e3b134.

**Comment by neeasade** [comment]
Works, still seeing lower ID's, but am able to perform operations on them with your new validation -- thanks.

**Comment by baskerville** [comment]
I finally found a reliable source: [the X11 protocol](http://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html).

We already know that the maximum length is at most 8, because the ID is an *uint32_t*, so could it be 7?

The protocol tells us that the *top three bits are guaranteed to be zero*, therefore the maximum value is `((1<<32)-1)>>3`, or `0x1fffffff` in base 16.

The correct length is 8.

**Comment by neeasade** [comment]
I see. Does that imply my issue is actually with my xorg/something else handing out technically invalid ID's to new windows?

**Comment by baskerville** [comment]
There was a misunderstanding: an ID is just a number. *0x0800003*, *0x800003*, *040000003*, and *8388611* are multiple representations of the **same** ID. As of b098530, printed IDs will have a fixed length.
