### ISSUE TITLE
Trouble clicking on focused windows.

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#576]
I can't seem to left-click on windows managed by bspwm due to e00b6c9e5c2b5d3f0555b6b9e62b46bd1077bf2f if `click_to_focus` is enabled. Reverting that commit fixes it.

Also, I'd expect click to focus to actually pass the click through (as it did before that commit). I have it enabled so that the window with which I'm interacting is always focused.

**Comment by baskerville** [comment]
Can you describe more clearly what the problem is?

I don't want to replay the initial commit for the reason I've given in the commit message.

**Comment by pezcore** [comment]
When the `click_to_focus` option is set to true with 

```
bspc config click_to_focus true
```

And then a window that is not currently focused is left-clicked on, there is no change in the focused window: the previously focused window remains focused and the click action has no appearent effect.

**Comment by baskerville** [comment]
I can't reproduce, `bspwmrc`?

**Comment by Stebalien** [comment]
Here's mine:

```bash
#!/bin/bash

source "$XDG_CONFIG_HOME/colors.sh" # Just sources some variables.

# Settings
bspc config border_width                  2
bspc config normal_border_color           "#555555"
bspc config focused_border_color          "$COLOR_HIGHLIGHT"
bspc config window_gap                    8
# Just wide enough 😄
bspc config split_ratio                   0.55
bspc config top_padding                   18
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config click_to_focus                true
bspc config presel_feedback_color         "$COLOR_HIGHLIGHT"

# Rules

bspc rule -a '*:zathura'                  state=tiled
bspc rule -a '*:pithos'                   desktop=Ten
bspc rule -a '*:keepassx'                 state=floating
bspc rule -a '*:yad'                      state=floating
bspc rule -a '*:display'                  center=on state=floating focus=on sticky=on
bspc rule -a '*:dropterm'                 state=floating sticky=on
bspc rule -a 'Firefox:Navigator'          private=on
bspc rule -a '*:emacs'                    private=on

# Setup monitors
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d {One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten}
    let i++
done
unset i


bspc wm --adopt-orphans
```

**Comment by Stebalien** [comment]
Also, I actually disagree with the reasoning in the message. If I click on a button, I want it to activate the button regardless of whether or not the window is focused. However, I also want windows to become focused when I interact with them.

Maybe something like `focus_on_interact` (covering all input)?

**Comment by alecive** [comment]
I generally agree with @Stebalien . It is somewhat expected to have focus on click with the event that passes through, especially if you come from more standard (non-tiling) WMs.

On the same topic, I would like to raise my issue: I have not set `click_to_focus` at all on my `bspwmrc`, so it should fall back to the default value (which I ignore). My `bspwm` repository is currently on come commits prior to https://github.com/baskerville/bspwm/commit/e00b6c9e5c2b5d3f0555b6b9e62b46bd1077bf2f. 

What happens in my machine is that, if I click on a button on an unfocused window, the window gains focus AND the click passes through. This is perfectly fine with me. My problem is that when I `ctrl+left click` on a button in the unfocused window (for example, I use it on firefox to open links on new tabs), the event passes through (i.e. the link is opened in the new tab), but the window DOES NOT gain focus.

So I agree with @Stebalien that if you want to keep this behavior, a config flag would be a good idea to add. Plus, also "complex" clicks such as `ctrl+click` should be treated the same way as the standard left click.

**Comment by baskerville** [comment]
@Stebalien Should be fixed by 7404946.

@alecive `ctrl + button1` isn't grabbed (unless `pointer_modifier` is `control`).

**Comment by Stebalien** [comment]
Works with `swallow_first_click` set to false but I still can't click on windows with it set to true. I'll leave it up to you whether or not to close this.

**Comment by alecive** [comment]
I currently have `pointer_modifier` set to `mod1`. What does it mean @baskerville ? I tried to look into `man bspwm` but it wasn't really helpful.
